### ISSUE TITLE
Aren't you ashamed of your inaducationness in front of community?

### ISSUE THREAD

**Issue by klesun** [klesun/sheet-midusic#94]
Add Tonality to Staff and draw flat/sharp/straight like it's done in academy. Yes, it's farer from bytes, but at least it will be understandable by other people.

**Comment by ArturKlesun** [comment]
Added key signature to Staff. Only issue left is that Tact still does not remember if some Nota goes sharp or becar and so on.

**Comment by klesun** [comment]
b1d4591
