### ISSUE TITLE
When we start playback in random place. it would be very nice of you to seek 2/1 for still held Nota-s and play them as well

### ISSUE THREAD

**Issue by klesun** [klesun/sheet-midusic#96]
Same would terrificly apply to graphical piano layout

For this probably a list with instruments that are held (example: 49 against 01) would be usefull

**Comment by ArturKlesun** [comment]
yeah, would be nice. implemented it for piano layout, but for sounding it's not such big priority

**Comment by klesun** [comment]
nah, too hard, too lazy, too minor significance
