### ISSUE TITLE
Separate Model from Component

### ISSUE THREAD

**Issue by klesun** [klesun/sheet-midusic#97]
It's wrong that Nota can not be instantiated without Accord. The only reason Nota has parent is event handling, what should be moved into separate class.
Take for a base AbstractPainter - make it like java's Component (or maybe even extend Component).

**Comment by ArturKlesun** [comment]
What if i said that even Component children does not need to know, who their parents are?

**Comment by klesun** [comment]
I would say it's how it should be done... one day. 
Separated Model from Component like a boss
